apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: azure-workload-identity-webhook
    git:
      url: https://github.com/Azure/azure-workload-identity
      ref: v1.4.1
      depth: 1
    newRootPath: charts/workload-identity-webhook
    ignorePaths:
    - ci/default-values.yaml
    - templates/azure-wi-webhook-controller-manager-ciliumnetworkpolicy.yaml
    - values.schema.json
