apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: azure-workload-identity-webhook
        git:
          depth: 1
          url: https://github.com/Azure/azure-workload-identity
          ref: "v1.4.1"
        includePaths:
          - charts/workload-identity-webhook/**/*
  - path: helm/azure-workload-identity-webhook
    contents:
    - path: .
      directory:
        path: vendor/azure-workload-identity-webhook/charts/workload-identity-webhook
      ignorePaths:
      - values.schema.json
      - Chart.yaml
      - templates/policyexception.yaml
