apiVersion: v2
name: azure-workload-identity-webhook
description: A Helm chart to install the azure-workload-identity webhook
type: application
version: 1.4.1
appVersion: v1.4.1
home: https://github.com/Azure/azure-workload-identity
sources:
  - https://github.com/Azure/azure-workload-identity
annotations:
  application.giantswarm.io/team: "phoenix"
