# ─── UPSTREAM ────────────────────────────────────────────────────────────────
upstream:
  nameOverride: azure-workload-identity-webhook

# ─── EXTRAS ──────────────────────────────────────────────────────────────────
networkPolicy:
  enabled: true

verticalPodAutoscaler:
  enabled: true

global:
  podSecurityStandards:
    enforced: true
