apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-wi-webhook-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  endpointSelector:
    matchLabels:
      app: '{{ template "workload-identity-webhook.name" . }}'
      azure-workload-identity.io/system: "true"
      chart: '{{ template "workload-identity-webhook.name" . }}'
      release: '{{ .Release.Name }}'
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
  egress:
  - toEntities:
    - cluster
    - kube-apiserver
